### ISSUE TITLE
capture error - wrong screen size using nanovna_capture.py (Windows 10, NanoVNA H)

### ISSUE THREAD

**Issue by krupis** [Ho-Ro/nanovna-tools#4] opened 2023-10-19 04:36 UTC
We have discussed about this a little bit:
https://github.com/NanoVNA-Saver/nanovna-saver/issues/676

After I have replaced:
```
#if bytestream == b'capture?\r\nch> ': # error message
```

with:
``` 
if captured_bytes == b'capture?\r\nch> ': # error message
```

to fix my initial issue:
```
 NameError: name 'bytestream' is not defined
```

I still cannot get to run this script on NanoVNA -H due to the following error:
```
C:\Users\petrikas.lu\Downloads\nanovna-tools-main\nanovna-tools-main>python nanovna_capture.py
capture error - wrong screen size?
```

Have you tried to run this on NanoVNA-H? Is that an issue related to NanoVNA - H? I tried using --help but does not seem to give any information regarding screen size.

**Comment by Ho-Ro** [comment] 2023-10-19 19:32
> Have you tried to run this on NanoVNA-H?

The script was developed on my NanoVNA-H.
I just checked it with my NanoVNA-H on a Windows 10 system (only user account, no special setup, nada).
The script should run out of the box, even the fixed typo was not seen unless something goes wrong with the communication.

```
c:\Users\...\projects\NanoVNA\nanovna-tools>python nanovna_capture.py

c:\Users\...\projects\NanoVNA\nanovna-tools>dir *.png
 ...
19.10.2023  20:57             8.295 NanoVNA-H_20231019_205757.png
```
![NanoVNA-H_20231019_205757](https://github.com/Ho-Ro/nanovna-tools/assets/12542359/1aba7ddc-6405-4303-bd34-858d2d627483)

Sorry, I do not know what's wrong with your system, you should try to debug a little bit to help me to support you. You should anyhow be familiar with python and the serial communication syntay when you want to roll your own analysis software.

Just spread some print(...) statements into the code, e.g. after line 114 (`if len( captured_bytes ) != 2 * size:`)
```python
    print( captured_bytes )
    print( len( captured_bytes ) )
```

This should give you a long output like this (only last part of the very long line shown), the last number may be different (my example shows the correct len).
```
...
\xff\xff\xff\xff\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\x00\x00\x00\x00\x00\x00\xff\xff\x00\x00\xff\xff\x00\x00\x00\x00\xff\xff\x00\x00\xff\xff\xff\xff\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00A@'
153600
capture error - wrong screen size?
```
If the output looks very different, please post here.

**Comment by Ho-Ro** [comment] 2023-10-20 16:55
As an extra service for @krupis I built the script [nanovna_communication_template.py](https://github.com/Ho-Ro/nanovna-tools/blob/main/nanovna_communication_template.py).
```
Command line template to send a serial shell command to NanoVNA:
- Connect via USB serial
- Encode the command string to bytearray
- Send the command + CR
- Get the command echo + CRLF
- Get the response + CRLF + prompt
- Format the response (remove CRLF + prompt)
- Decode the response bytearray to string
- Write the response string to stdout
```
Please play with this tool to debug your system issues.

**Comment by Ho-Ro** [comment] 2023-10-31 08:03
Either @krupis has solved his problem or is no longer interested in this topic - either way, I'm closing here. You can contact me here if you are still interested. I cannot reproduce the error, neither under Linux nor under Windows.

**Closed by Ho-Ro** 2023-10-31 08:03 UTC
Labels: Serial Communication, Not reproducible
